---
- name: Configure the web server
  hosts: all
  remote_user: samrap
  roles:
    - base
    - ghost
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    SYSTOOLS_BACKUPS_S3_ENDPOINT: "{{ SYSTOOLS_BACKUPS_S3_ENDPOINT }}"
    SYSTOOLS_BACKUPS_S3_REGION: "{{ SYSTOOLS_BACKUPS_S3_REGION }}"
    SYSTOOLS_BACKUPS_S3_BUCKET: "{{ SYSTOOLS_BACKUPS_S3_BUCKET }}"
